import Head from "next/head";
import Image from "next/image";
import TestComponent from "./components/TestComponent";

export default function Home() {
	return (
		<>
			<Head>
				<title>Aeon Tactics</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
			</Head>
			<main className="flex min-h-screen flex-col items-center justify-between p-24">
				<div className="flex flex-col justify-content">
					<h1 className="font-bold">Aeon Tactics</h1>
					<p className="flex text-center">
						Aeon Tactics is a web based autobattler game. Build your team,
						dominate your opponents, claim victory!
					</p>
					<TestComponent />
				</div>
			</main>
		</>
	);
}
