import Head from "next/head";
import Image from "next/image";
import Community from "./components/Community";
import Footer from "./components/Footer";
import Hero from "./components/Hero";
import Navbar from "./components/Navbar";
import PlayNow from "./components/PlayNow";
import Team from "./components/Team";

// import { Community, Footer, Hero, Navbar, PlayNow, Team } from "./components";

export default function Home() {
	return (
		<>
			<Head>
				<title>Aeon Tactics</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
			</Head>
			<Navbar />
			<main className="flex min-h-screen flex-col items-center justify-between bg-mirage-950">
				<Hero />
				<PlayNow />
				<Community />
				<Team />
				<Footer />
			</main>
		</>
	);
}
